# -*- python -*-
Import('env')

lenv = env.Clone()
sources = lenv.Glob('[!S]*.cc')
lenv.StaticLibrary('partition', sources)

for target in ('sph-htm-index',
               'sph-partition',
               'sph-partition-matches',
               'sph-duplicate',
               'sph-estimate-stats',
              ):
    source = ''.join(map(lambda s: s.title(), target.split('-'))) + '.cc'
    penv = env.Clone()
    penv.Append(LIBPATH=['.'])
    penv.Prepend(LIBS=['partition'])
    program = penv.Program(target, [source])
    penv.Install('$prefix/bin', program)
