# -*- python -*-
from lsst.sconsUtils import env

lenv = env.Clone()
sources = lenv.Glob('[!S]*.cc')
lenv.StaticLibrary('partition', sources)

for target in ('sph-htm-index',
               'sph-partition',
               'sph-partition-matches',
               'sph-duplicate',
               'sph-estimate-stats',
              ):
    source = ''.join(map(lambda s: s.title(), target.split('-'))) + '.cc'
    penv = env.Clone()
    penv.Append(LIBPATH=['.'])
    # retrieving libs with sconsUtils
    libs=['partition']+env.getLibs("main")
    penv.Prepend(LIBS=(libs))
    program = penv.Program(target, [source])
    Default(program)
    penv.Install('$prefix/bin', program)
